outbound:
    serviceReferences:
    - name: choreo:///diyasen/sycodoca/acrhvt/9bce3/v1/PUBLIC
      connectionConfig: 01ef0703-55f2-1176-8f5a-d5d715aafc3c
      env:
      - from: ServiceURL
        to: https://d3a34988-bf91-42db-a5dc-056dd611b04f-dev.e1-us-cdp-2.choreoapis.dev/sycodoca/chatapi/chat-api-9bc/v1
      - from: ConsumerKey
        to: ejkE43QRioSyncIl7zhr46E66tQa
      - from: ConsumerSecret
        to: *****************
      - from: TokenURL
        to: https://sts.choreo.dev/oauth2/token
